server:
  port: 10012
  tomcat:
    threads:
      max: 200
      min-spare: 20

spring:
  application:
    name: trade
  profiles:
    active: dev

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  main:
    allow-circular-references: true
  data:
    redis:
      lettuce:
        pool:
          max-idle: 10
          max-active: 20
          min-idle: 1

  threads:
    virtual:
      enabled: true

# ????????
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

mqtt:
  host: tcp://192.168.1.109:18083
  clientId: data
  username: admin
  password: aa123456789
  topic: ticker


logging:
  level:
    root: info
    sql: info
    web: info
  file:
    name: trade