
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/binary-option?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&rewriteBatchedStatements=true
          username: root
          password: 12345678
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-pool-size: 5
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/binary-option-kline?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&rewriteBatchedStatements=true
          username: root
          password: 12345678
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-pool-size: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
      password: Aq23-hjPwFB3mBDNFp3W1
  boot:
    admin:
      client:
        url: http://127.0.0.1:10000