server:
  port: 10002
  tomcat:
    threads:
      max: 300

spring:
  application:
    name: business
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/binary-option?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 12345678
    type: com.mysql.cj.jdbc.MysqlDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  main:
    allow-circular-references: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
      password: Aq23-hjPwFB3mBDNFp3W1
      lettuce:
        pool:
          max-idle: 10
          max-active: 20
          min-idle: 1


  boot:
    admin:
      client:
        url: http://127.0.0.1:10000

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info
    sql: info
    web: info
  file:
    name: business

sa-token:
  # token ??????? cookie ???
  token-name: access-auth-token
  # token ????????? ??30??-1 ??????
  timeout: 604800
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: -1
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: false
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: false
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: random-128
  # ????????
  is-log: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl