server:
  port: 10001

spring:
  application:
    name: input

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/binary-option?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 12345678
    type: com.mysql.cj.jdbc.MysqlDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  main:
    allow-circular-references: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
      password: Aq23-hjPwFB3mBDNFp3W1
      lettuce:
        pool:
          max-idle: 10
          max-active: 20
          min-idle: 1


  boot:
    admin:
      client:
        url: http://127.0.0.1:10000

  threads:
    virtual:
      enabled: true

# ????????
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

mqtt:
  host: tcp://localhost:18083 # MQTT ?????
  clientId: data
  username: admin # ??
  password: aa123456789 # ??
  topic: test/topic


logging:
  level:
    root: info
    sql: info
    web: info
  file:
    name: input